[package]
name = "zamanKapsulu"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.17"
borsh = "1.5.1"
borsh-derive = "1.5.1"
thiserror = "1.0.24"


[lib]
crate-type = ["cdylib", "lib"]
name = "zamanKapsulu"